name: $(Build.BuildID) - dgca-verifier-app-android

trigger:
  branches:
    include:
    - develop
    - feature/*
    - releases/*
    - azure-pipelines
 

pr:
  branches:
    include:
    - develop
    - releases/*
 
resources:
  repositories:
  - repository: dgca-app-core-android
    type: github
    name: eu-digital-green-certificates/dgca-app-core-android
    ref: 'main'
    endpoint: 'GitHub - it-eucert-team'

pool:
  vmImage: 'ubuntu-latest'

variables:
  versionCounter: $[counter(variables['Build.SourceBranch'], 100)] 

stages:
- stage: Build
  jobs:
  - job: InitPipeline

    steps:
    - checkout: self
      clean: true
    - checkout: dgca-app-core-android

    - task: Bash@3
      displayName: set init value
      name: checkBuildCommit
      inputs:
        targetType: 'inline'
        script: |
          echo "Check trigger pipeline var"
          echo $(versionCounter) 
          echo "commit message: $(Build.SourceVersionMessage)"
          echo "##vso[task.setvariable variable=message;isOutput=true;]$(Build.SourceVersionMessage)"
          GIT_MESSAGE="$(Build.SourceVersionMessage)"
          BUILD_REASON=$(Build.Reason)
 
          echo "buildReason: $BUILD_REASON"
          echo "gitMessage: $GIT_MESSAGE"

          echo "##vso[task.setvariable variable=build;isOutput=true;]$(build)"
          echo "##vso[task.setvariable variable=debug;isOutput=true;]$(debug)"
          echo "##vso[task.setvariable variable=release;isOutput=true;]$(release)"
          echo "##vso[task.setvariable variable=appcenter;isOutput=true;]$(appcenter)"
          echo "##vso[task.setvariable variable=store;isOutput=true;]$(store)"
          
          if [[ ! BUILD_REASON == 'IndividualCI' ]]; then
            echo "Set variable for Build Reason Individual CI"
            
            if [[ ! $GIT_MESSAGE == *"#build"* ]]; then
                echo "Not a build commit. Stopping the execution of the build job."
            fi

            if [[ $GIT_MESSAGE == *"#build-release"* ]]; then
              echo "set variabili build e release a true"
              echo "##vso[task.setvariable variable=build;isOutput=true;]true"
              echo "##vso[task.setvariable variable=release;isOutput=true;]true"
            fi

            if [[ $GIT_MESSAGE == *"#build-debug"* ]]; then
              echo "set variabili build e debug a true"
              echo "##vso[task.setvariable variable=build;isOutput=true;]true"
              echo "##vso[task.setvariable variable=debug;isOutput=true;]true"
            fi

            if [[ $GIT_MESSAGE == *"#appcenter"* ]]; then
              echo "set variabili appcenter a true"
              echo "##vso[task.setvariable variable=appcenter;isOutput=true;]true"
            fi

            if [[ $GIT_MESSAGE == *"#store"* ]]; then
              echo "set variabili store a true"
              echo "##vso[task.setvariable variable=store;isOutput=true;]true"
            fi
          fi

          if [[ BUILD_REASON == 'PullRequest' ]]; then
              echo "Set variable for Build Reason PullRequest "
              echo "##vso[task.setvariable variable=build;isOutput=true;]true"
              echo "##vso[task.setvariable variable=debug;isOutput=true;]true"
          fi

    - bash: |
         echo 'message $(checkBuildCommit.message)'
         echo 'build $(checkBuildCommit.build)'
         echo 'debug $(checkBuildCommit.debug)'
         echo 'release $(checkBuildCommit.release)'
         echo 'appcenter $(checkBuildCommit.appcenter)'
         echo 'store $(checkBuildCommit.store)'
    #     echo '$(NUMBER_OF_COMMITS)'
    #     echo '$(MAJOR).$(MINOR).$(PATCH)-dev'

  - job: BuildApk
    dependsOn: InitPipeline
    condition: and(succeeded(), eq(dependencies.InitPipeline.outputs['checkBuildCommit.build'], true))
    variables: 
      build: $[ dependencies.InitPipeline.outputs['checkBuildCommit.build'] ]
      debug: $[ dependencies.InitPipeline.outputs['checkBuildCommit.debug'] ]
      release: $[ dependencies.InitPipeline.outputs['checkBuildCommit.release'] ]
      appcenter: $[ dependencies.InitPipeline.outputs['checkBuildCommit.appcenter'] ]
      store: $[ dependencies.InitPipeline.outputs['checkBuildCommit.store'] ]

    steps:
    - checkout: self
      clean: true
    - checkout: dgca-app-core-android
    
    - task: ExtractVersionFromTag@1
      inputs:
        projectFolderPath: '$(Build.SourcesDirectory)'
    
    - bash: |
         echo 'message $(message)'
         echo 'build $(build)'
         echo 'debug $(debug)'
         echo 'release $(release)'
         echo 'appcenter $(appcenter)'
         echo 'store $(store)'
         echo '$(NUMBER_OF_COMMITS)'
         echo '$(MAJOR).$(MINOR).$(PATCH)-dev'
    
    - task: UpdateAndroidVersionGradle@1
      inputs:
        buildGradlePath: 'it-dgc-verificaC19-android/app/build.gradle'
        versionCode: '$(NUMBER_OF_COMMITS)'
        # versionCode: '$(versionCounter)'
        versionName: '$(MAJOR).$(MINOR).$(PATCH)-dev'
        # versionName: '$(version-name)-dev'
        ${{ if eq(variables['release'],true) }}:
          versionName: '$(MAJOR).$(MINOR).$(PATCH)'

    - task: SonarQubePrepare@4
      inputs:
        SonarQube: 'SonarQube Azure 8.9'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: '$(System.TeamProject)_it-dgc-verificaC19-android'
        cliProjectName: '$(System.TeamProject)_it-dgc-verificaC19-android'
        cliProjectVersion: '$(Build.SourceBranchName)_$(Build.SourceVersion)'
        cliSources: '.'
        extraProperties: |
          sonar.java.binaries=.
          sonar.exclusions=**/CCReport*/**
      continueOnError: true

    - task: SonarQubeAnalyze@4
      continueOnError: true
      condition: succeeded()

    - task: SonarQubePublish@4
      inputs:
        pollingTimeoutSec: '300'
      continueOnError: true
      condition: succeeded()
    - task: Gradle@2
      inputs:
        gradleWrapperFile: 'it-dgc-verificaC19-android/gradlew'
        workingDirectory: 'it-dgc-verificaC19-android'
        ${{ if eq(variables['release'],true) }}:
          tasks: 'assembleRelease'
        ${{ if eq(variables['debug'],true) }}:
          tasks: 'assembleDebug'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        gradleOptions: '-Xmx3072m'
        sonarQubeRunAnalysis: false
        spotBugsAnalysis: false

    - task: CopyFiles@2
      inputs:
        contents: '**/*.apk'
        targetFolder: '$(build.artifactStagingDirectory)'

    - task: AndroidSigning@3
      inputs:
        apkFiles: '$(build.artifactStagingDirectory)/it-dgc-verificaC19-android/app/build/outputs/apk/release/app-release-unsigned.apk'
        apksignerKeystoreFile: 'android-c19-key.jks'
        apksignerKeystorePassword: '$(keystorepassword)'
        apksignerKeystoreAlias: '$(keystorealias)'
        apksignerKeyPassword: '$(keystorepassword)'
        zipalign: false

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(build.artifactStagingDirectory)/it-dgc-verificaC19-android/app/build/outputs/apk/release/app-release-unsigned.apk'
        artifact: 'apk'
        publishLocation: 'pipeline'

    # verificare eventuali condizioni sui rami per eseguire questo step (ad esempio non sulla feature, ma solo su develop e release?)
    - task: Gradle@2
      inputs:
        gradleWrapperFile: 'it-dgc-verificaC19-android/gradlew'
        workingDirectory: 'it-dgc-verificaC19-android'
        tasks: ':app:bundleRelease'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        gradleOptions: '-Xmx3072m'
        sonarQubeRunAnalysis: false
        spotBugsAnalysis: false

    - task: CopyFiles@2
      inputs:
        contents: '**/*.aab'
        targetFolder: '$(build.artifactStagingDirectory)'

    - task: AndroidSigning@2
      inputs:
        apkFiles: '$(build.artifactStagingDirectory)/it-dgc-verificaC19-android/app/build/outputs/bundle/release/app-release.aab'
        jarsignerKeystoreFile: 'android-c19-key.jks'
        jarsignerKeystorePassword: '$(keystorepassword)'
        jarsignerKeystoreAlias: '$(keystorealias)'
        jarsignerKeyPassword: '$(keystorepassword)'
        jarsignerArguments: '-sigalg SHA256withRSA -digestalg SHA-256'
    
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(build.artifactStagingDirectory)/it-dgc-verificaC19-android/app/build/outputs/bundle/release/app-release.aab'
        artifact: 'bundle'
        publishLocation: 'pipeline'
    
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: 'it-dgc-verificaC19-android/metadata/release-notes.xml'
        artifact: 'release-notes'
        publishLocation: 'pipeline'

- stage: AppCenterRelease
  dependsOn: Build
  condition: and(succeeded(), eq(dependencies.Build.InitPipeline.outputs['checkBuildCommit.appcenter'], true))
  variables: 
    build: $[ dependencies.Build.InitPipeline.outputs['checkBuildCommit.build'] ]
    debug: $[ dependencies.Build.InitPipeline.outputs['checkBuildCommit.debug'] ]
    release: $[ dependencies.Build.InitPipeline.outputs['checkBuildCommit.release'] ]
    appcenter: $[ dependencies.Build.InitPipeline.outputs['checkBuildCommit.appcenter'] ]
    store: $[ dependencies.Build.InitPipeline.outputs['checkBuildCommit.store'] ]
  jobs:
    - deployment: AppCenterRelease   # name of the deployment job, A-Z, a-z, 0-9, and underscore. The word "deploy" is a keyword and is unsupported as the deployment name.
      displayName: Release to AppCenter  # friendly name to display in the UI
      # pool:                # see pool schema
      #   name: string       # Use only global level variables for defining a pool name. Stage/job level variables are not supported to define pool name.
      #   demands: string | [ string ]
      workspace:
        clean: all # what to clean up before the job runs
      # dependsOn: string
      # condition: string
      # continueOnError: boolean                # 'true' if future jobs should run even if this job fails; defaults to 'false'
      # container: containerReference # container to run this job inside
      # services: { string: string | container } # container resources to run as a service container
      # timeoutInMinutes: nonEmptyString        # how long to run the job before automatically cancelling
      # cancelTimeoutInMinutes: nonEmptyString  # how much time to give 'run always even if cancelled tasks' before killing them
      # variables: # several syntaxes, see specific section
      environment: AppCenter  # target environment name and optionally a resource name to record the deployment history; format: <environment-name>.<resource-name>
      strategy:
        runOnce:    #rolling, canary are the other strategies that are supported
          preDeploy: 
           steps:
            - script: |
               echo "Publish to appcenter - var store $(store)"
            - task: DownloadPipelineArtifact@2
              inputs:
                buildType: 'specific'
                project: 'd8761144-9102-412a-9be9-76b96650fb00'
                definition: '12'
                specificBuildWithTriggering: true
                buildVersionToDownload: 'latest'
                targetPath: '$(Pipeline.Workspace)'
          deploy:
            steps:
            - task: AppCenterDistribute@3
              inputs:
                serverEndpoint: 'DGC-App'
                appSlug: 'sogei/it-dgc-verificaC19-android'
                appFile: '$(Pipeline.Workspace)/apk/app-release-unsigned.apk'
                symbolsOption: 'Android'
                releaseNotesOption: 'file'
                releaseNotesFile: '$(PIPELINE.WORKSPACE)/release-notes/release-notes.xml'
                destinationType: 'groups'
                isSilent: true
              


- stage: GooglePlayTestRelease
  dependsOn: Build
  condition: and(succeeded(), eq(dependencies.Build.InitPipeline.outputs['checkBuildCommit.store'], true))
  variables: 
    build: $[ dependencies.Build.InitPipeline.outputs['checkBuildCommit.build'] ]
    debug: $[ dependencies.Build.InitPipeline.outputs['checkBuildCommit.debug'] ]
    release: $[ dependencies.Build.InitPipeline.outputs['checkBuildCommit.release'] ]
    appcenter: $[ dependencies.Build.InitPipeline.outputs['checkBuildCommit.appcenter'] ]
    store: $[ dependencies.Build.InitPipeline.outputs['checkBuildCommit.store'] ]
  jobs:
    - deployment: GooglePlayRelease   # name of the deployment job, A-Z, a-z, 0-9, and underscore. The word "deploy" is a keyword and is unsupported as the deployment name.
      displayName: Release to Google Play  # friendly name to display in the UI
        # pool:                # see pool schema
        #   name: string       # Use only global level variables for defining a pool name. Stage/job level variables are not supported to define pool name.
        #   demands: string | [ string ]
      workspace:
           clean: all # what to clean up before the job runs
        # dependsOn: string
        # condition: string
        # continueOnError: boolean                # 'true' if future jobs should run even if this job fails; defaults to 'false'
        # container: containerReference # container to run this job inside
        # services: { string: string | container } # container resources to run as a service container
        # timeoutInMinutes: nonEmptyString        # how long to run the job before automatically cancelling
        # cancelTimeoutInMinutes: nonEmptyString  # how much time to give 'run always even if cancelled tasks' before killing them
        # variables: # several syntaxes, see specific section
      environment: AndroidStoreTest  # target environment name and optionally a resource name to record the deployment history; format: <environment-name>.<resource-name>
      strategy:
        runOnce:    #rolling, canary are the other strategies that are supported
          preDeploy: 
           steps:
            - task: DownloadPipelineArtifact@2
              inputs:
                buildType: 'specific'
                project: 'd8761144-9102-412a-9be9-76b96650fb00'
                definition: '12'
                specificBuildWithTriggering: true
                buildVersionToDownload: 'latest'
                targetPath: '$(Pipeline.Workspace)'
            - script: |
                echo "Publish to store - var store $(store)"

        #   - task: GooglePlayReleaseBundle@3
        #       inputs:
        #         serviceConnection: 'verificac19-google-play'
        #         applicationId: 'it.ministerodellasalute.verificaC19'
        #         bundleFile: '$(Pipeline.Workspace)/it-dgc-verificaC19-android/bundle/app-release.aab'
        #         track: 'internal'
        #         changeLogFile: '$(Pipeline.Workspace)/it-dgc-verificaC19-android/release-notes/release-notes.xml'
        #         languageCode: 'en-GB'      
